.TH copy_example 2 "" "" Mikenet
.SH NAME
copy_example
.SH SYNOPSIS

#include <mikenet/simulator.h>

function prototype in example.h

void copy_example(Example *to, Example *from);

.SH DEFINITION
Copies the contents of the 'from' example to the 'to' example.  See create_example(2) for more.

.SH SEE ALSO
create_example(2), Example(4)
