CLAMP Input ALL FULL 0 0
TARGET Output 2 FULL 0
;
CLAMP Input ALL FULL 1 0
TARGET Output 2 FULL 1
;
CLAMP Input ALL FULL 0 1
TARGET Output 2 FULL 1
;
CLAMP Input ALL FULL 1 1 
TARGET Output 2 FULL 0
;

