CLAMP Input ALL FULL -1 -1
TARGET Output 2 FULL -1
;
CLAMP Input ALL FULL 1 -1
TARGET Output 2 FULL 1
;
CLAMP Input ALL FULL -1 1
TARGET Output 2 FULL 1
;
CLAMP Input ALL FULL 1 1 
TARGET Output 2 FULL -1
;

